server:
  port: 8903
spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: shopoo-spring-cloud-gateway
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      discovery:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
      config:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
  config:
    import:
      - nacos:common-oauth2-resource-server.yaml
      - nacos:spring-cloud-gateway.yaml
      - nacos:spring-cloud-gateway-route.yaml
      - nacos:common.yaml
      - nacos:common-jdbc.yaml
      - nacos:common-redis.yaml
      - nacos:common-rocketmq.yaml
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      service-config:
        chatgpt:
          group-name: chatgpt
          order: 1
      version: openapi3