server:
  port: 8903
spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: shopoo-spring-cloud-gateway
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      discovery:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
      config:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
  config:
    import:
      - nacos:common-oauth2-resource-server.yaml
      - nacos:spring-cloud-gateway.yaml
      - nacos:spring-cloud-gateway-route.yaml
      - nacos:shopoo-common.yaml
      - nacos:shopoo-common-jdbc.yaml
      - nacos:shopoo-common-redis.yaml
      - nacos:shopoo-common-dubbo.yaml
      - nacos:shopoo-common-rocketmq.yaml
